apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarboppgave
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarboppgave/veilarboppgave:{{version}}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  port: 8080
  webproxy: true
  ingresses:
    - https://veilarboppgave-q1.nais.preprod.local
    - https://app-q1.adeo.no/veilarboppgave
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarboppgave
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /oracle/data/dev/creds/veilarboppgave_q1-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /kv/preprod/fss/veilarboppgave/q1
        mountPath: /var/run/secrets/nais.io/vault
  envFrom:
    - configmap: pto-config
  prometheus:
    enabled: true
    path: veilarboppgave/internal/prometheus
  readiness:
    path: veilarboppgave/internal/health/readiness
    initialDelay: 30
  liveness:
    path: veilarboppgave/internal/health/liveness
    initialDelay: 30
  resources:
    limits:
      cpu: "2"
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
