apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarboppgave
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarboppgave/veilarboppgave:{{version}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  port: 8080
  webproxy: true
  ingresses:
    - https://veilarboppgave.nais.adeo.no
    - https://app.adeo.no/veilarboppgave
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvveilarboppgave
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarboppgave/default
        mountPath: /var/run/secrets/nais.io/vault
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
  envFrom:
    - configmap: pto-config
  prometheus:
    enabled: true
    path: veilarboppgave/internal/prometheus
  readiness:
    path: veilarboppgave/internal/health/readiness
    initialDelay: 45
  liveness:
    path: veilarboppgave/internal/health/liveness
    initialDelay: 45
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 512Mi
