CREATE TABLE OPPGAVEHISTORIKK (
  ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
  AKTOERID VARCHAR(255) NOT NULL,
  GSAK_ID VARCHAR(255) NOT NULL,
  TEMA VARCHAR(255) NOT NULL,
  TYPE VARCHAR(255) NOT NULL,
  OPPRETTET_AV_IDENT VARCHAR(255) NOT NULL,
  OPPRETTET_TIDSPUNKT TIMESTAMP NOT NULL,
  PRIMARY KEY(ID)
)