apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarboppgave
  namespace: obo
  labels:
    team: obo
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  port: 8080
  webproxy: true
  ingresses:
    - https://veilarboppgave.intern.nav.no
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: db-custom-1-3840
        databases:
          - name: veilarboppgave
            envVarPrefix: DB
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbpersonflate
          namespace: poao
    outbound:
      rules:
        - application: poao-tilgang
          namespace: poao
        - application: veilarbperson
          namespace: obo
        - application: norg2
          namespace: org
      external:
        - host: pdl-api.prod-fss-pub.nais.io
        - host: oppgave.prod-fss-pub.nais.io
  env:
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: POAO_TILGANG_SCOPE
      value: api://prod-gcp.poao.poao-tilgang/.default
    - name: VEILARBPERSON_URL
      value: http://veilarbperson.obo/veilarbperson
    - name: VEILARBPERSON_SCOPE
      value: api://prod-gcp.obo.veilarbperson/.default
    - name: NORG2_URL
      value: http://norg2.org/norg2
  prometheus:
    enabled: true
    path: veilarboppgave/internal/prometheus
  readiness:
    path: veilarboppgave/internal/health/readiness
    initialDelay: 45
  liveness:
    path: veilarboppgave/internal/health/liveness
    initialDelay: 45
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 512Mi
