apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarboppgave
  namespace: obo
  labels:
    team: obo
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  port: 8080
  webproxy: true
  ingresses:
    - https://veilarboppgave.intern.nav.no
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: veilarboppgave
            envVarPrefix: DB
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbpersonflate
          namespace: poao

  env:
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: POAO_TILGANG_SCOPE
      value: api://prod-gcp.poao.poao-tilgang/.default
  prometheus:
    enabled: true
    path: veilarboppgave/internal/prometheus
  readiness:
    path: veilarboppgave/internal/health/readiness
    initialDelay: 45
  liveness:
    path: veilarboppgave/internal/health/liveness
    initialDelay: 45
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 512Mi
